# Generated by Django 5.0.6 on 2024-06-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0003_alter_campeonato_categoria_alter_campeonato_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeonato',
            name='principal',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NÃO', 'Não')], default='', max_length=5),
        ),
    ]
