# Generated by Django 5.0.6 on 2024-06-06 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curto', models.CharField(max_length=50)),
                ('nome_completo', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('simbolo', models.CharField(max_length=100)),
                ('historico', models.TextField()),
                ('publicado', models.BooleanField(default=True)),
                ('data_registro', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
