# Generated by Django 5.0.6 on 2024-06-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='times',
            name='simbolo',
            field=models.ImageField(upload_to='simbolo/%Y/%m/%d'),
        ),
    ]
