# Generated by Django 5.0.6 on 2024-06-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_alter_times_simbolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='times',
            name='simbolo',
            field=models.ImageField(upload_to='escudo/%Y/%m/%d'),
        ),
    ]
