# Generated by Django 5.0.6 on 2024-06-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_alter_times_simbolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='times',
            name='simbolo',
            field=models.ImageField(upload_to='simbolo/%Y/%m/%d'),
        ),
    ]
