# Generated by Django 5.0.6 on 2024-06-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_remove_times_data_registro_remove_times_publicado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='times',
            name='simbolo',
            field=models.ImageField(blank=True, upload_to='simbolo/%Y/%m/%d'),
        ),
    ]
