# Generated by Django 5.0.6 on 2024-06-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0004_alter_campeonato_principal'),
        ('galeria', '0010_alter_times_titulos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='times',
            name='titulos',
            field=models.ManyToManyField(blank=True, related_name='titulos', to='campeonatos.campeonato'),
        ),
    ]
