# Generated by Django 5.0.6 on 2024-06-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0004_alter_campeonato_principal'),
        ('galeria', '0011_alter_times_titulos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='times',
            name='titulos',
            field=models.ManyToManyField(related_name='titulo', to='campeonatos.campeonato'),
        ),
    ]
