# Generated by Django 5.0.6 on 2024-06-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0012_alter_times_titulos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='times',
            name='titulos',
        ),
        migrations.AddField(
            model_name='times',
            name='titulos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
