# Generated by Django 5.0.6 on 2024-06-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0004_alter_campeonato_principal'),
        ('galeria', '0015_declararcampeao'),
    ]

    operations = [
        migrations.AddField(
            model_name='times',
            name='titulos',
            field=models.ManyToManyField(through='galeria.DeclararCampeao', to='campeonatos.campeonato'),
        ),
    ]
