# Generated by Django 5.0.6 on 2024-06-09 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0017_declararcampeao_pontuacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declararcampeao',
            name='pontuacao',
        ),
    ]
