# Generated by Django 5.0.6 on 2024-06-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0018_remove_declararcampeao_pontuacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='declararcampeao',
            name='pontuacao',
            field=models.IntegerField(default=0),
        ),
    ]
