# Generated by Django 5.0.6 on 2024-07-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0019_declararcampeao_pontuacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='times',
            name='descricao_mascote',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='times',
            name='foto_mascote',
            field=models.ImageField(blank=True, upload_to='mascote/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='times',
            name='nome_mascote',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
